name: Publish

on:
  release:
    types:
      - created
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        enable-cache: true
        cache-dependency-glob: |
          pyproject.toml

    - name: Install python
      run: uv python install

    - name: Install dependencies
      run: uv sync

    - name: Build
      run: uv build

    - name: Publish
      run: uv publish


