name: Test&Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        enable-cache: true
        cache-dependency-glob: |
          pyproject.toml
    - name: Install python
      run: uv python install
    - name: Install deps 
      run: uv sync --only-group lint
    - name: Run ruff
      run: uv run ruff check
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        enable-cache: true
        cache-dependency-glob: |
          pyproject.toml

    - name: Install python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        # TODO: install extras?
        uv sync --group test

    - name: Test
      run: |
        uv run pytest

